function radio() {
  return [
    {
      id: 0,
      name: "Radio Kantipur",
      logo: "https://radio-jcss-cdn.ekantipur.com/images/kfm_logo.png",
      audio: "https://radio-broadcast.ekantipur.com/stream",
      active: true,
    },
    {
      id: 1,
      name: "Kalika FM",
      logo: "https://cdn-radiotime-logos.tunein.com/s48026g.png",
      audio: "https://streaming.softnep.net:10828/stream?type=http&nocache=3662",
      active: false,
    },
    {
      id: 2,
      name: "Radio Nepal",
      logo: "https://images.hamro-files.com/Dn7WXDJ4gUldD71C1tjYlg09IPc=/500x500/https://sgp1.digitaloceanspaces.com/everestdb/hamropatro-backend/radio/7b57852c-4a14-4695-8dc5-9879f6be8780",
      audio: "https://radionepal.news/live",
      active: false,
    },
    {
      id: 3,
      name: "Ujyaalo 90 Network",
      logo: "https://static-media.streema.com/media/cache/de/39/de395c2cef8231ce24009ace8d2c63a7.jpg",
      audio: "https://stream.zeno.fm/h527zwd11uquv",
      active: false,
    },
    {
      id: 4,
      name: "Radio Audio",
      logo: "https://cdn-profiles.tunein.com/s105813/images/logog.png",
      audio: "https://stream.zeno.fm/fvrx47wpg0quv",
      active: false,
    },
    {
      id: 5,
      name: "Radio Annapurna Nepal",
      logo: "https://cdn-radiotime-logos.tunein.com/s180463q.png",
      audio: "https://streaming.softnep.net:10980/stream?type=http&nocache=214122",
      active: false,
    },
    {
      id: 6,
      name: "Capital FM",
      logo: "https://www.cfmonair.com/uploads/images/161025986597c56cf24e250e6a1799ae4b285581.jpg",
      audio: "https://streaming.softnep.net:10982/;stream.nsv&type=mp3&volume=10",
      active: false,
    },
    {
      id: 7,
      name: "Hits FM",
      logo: "https://static-media.streema.com/media/cache/a5/d8/a5d827f31d007b629c059f19f35cb59b.jpg",
      audio: "https://usa15.fastcast4u.com/proxy/hitsfm912?mp=/1",
      active: false,
    },
    {
      id: 8,
      name: "Mithilanchal FM",
      logo: "https://dbs.radioline.fr/pictures/radio_04646c9dbf216aede926c85722705814/logo200.jpg?size=200",
      audio: "https://live.itech.host:8645/stream",
      active: false,
    },
    {
      id: 9,
      name: "SomaFM: Groove Salad",
      logo: "https://cdn-radiotime-logos.tunein.com/s34091g.png",
      audio: "https://ice2.somafm.com/groovesalad-128-mp3",
      active: false,
    },
    {
      id: 10,
      name: "iHeartRadio",
      logo: "https://cdn-profiles.tunein.com/s25195/images/logog.png",
      audio: "https://c13.prod.playlists.ihrhls.com/2759/playlist.m3u8",
      active: false,
    },
    {
      id: 11,
      name: "Fun Radio",
      logo: "https://cdn-radiotime-logos.tunein.com/s1342g.png",
      audio: "https://scdn.nrjaudio.fm/audio1/fr/30401/mp3_128.mp3",
      active: false,
    },
    {
      id: 12,
      name: "Skyrock",
      logo: "https://cdn-radiotime-logos.tunein.com/s1350g.png",
      audio: "https://icecast.skyrock.net/s/natio_mp3_128k",
      active: false,
    },
    {
      id: 13,
      name: "BBC Radio 1 (UK)",
      logo: "https://cdn-radiotime-logos.tunein.com/s24939g.png",
      audio: "http://stream.live.vc.bbcmedia.co.uk/bbc_radio_one",
      active: true,
    },
    {
      id: 14,
      name: "NRJ (France)",
      logo: "http://localhost:3001/assets/logoalumni.png",
      audio: "https://scdn.nrjaudio.fm/audio1/fr/30001/mp3_128.mp3",
      active: false,
    },
    {
      id: 15,
      name: "RAI Radio 1 (Italy)",
      logo: "https://cdn-radiotime-logos.tunein.com/s6821g.png",
      audio: "http://icestreaming.rai.it/1.mp3",
      active: false,
    },
    {
      id: 16,
      name: "Radio Maria (Poland)",
      logo: "https://cdn-radiotime-logos.tunein.com/s30420g.png",
      audio: "http://94.23.202.149:8000/live",
      active: false,
    },
    {
      id: 17,
      name: "Studio Brussel (Belgium)",
      logo: "http://localhost:3001/assets/logoalumni.png",
      audio: "https://icecast.vrtcdn.be/stubru-high.mp3",
      active: false,
    },
    {
      id: 18,
      name: "Radio Suisse Romande (Switzerland)",
      logo: "https://cdn-radiotime-logos.tunein.com/s6795g.png",
      audio: "https://stream.srg-ssr.ch/m/rsj/mp3_128",
      active: false,
    },
    {
      id: 19,
      name: "Radio Classique (France)",
      logo: "http://localhost:3001/assets/logoalumni.png",
      audio: "https://radioclassique.ice.infomaniak.ch/radioclassique-high.mp3",
      active: false,
    },
    {
      id: 20,
      name: "Sky Radio (Netherlands)",
      logo: "https://cdn-radiotime-logos.tunein.com/s6530g.png",
      audio: "http://19993.live.streamtheworld.com/SKYRADIO.mp3",
      active: false,
    },
  ];
}

export default radio;
